version: '3'

services:
  api-server:
    build: .
    ports:
      - "3000:8080"
    env_file:
      - ./src/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    